### ISSUE TITLE
Enhancement - Add an "Are You Sure?" prompt for delete

### ISSUE THREAD

**Issue by yb0rc1ty** [ordercloud-api/ngx-shopper#159]
Currently, when a user is looking at their personal address, there is not "Are You Sure?" prompt if a user opts to delete the address. This is frustrating, especially if a user accidentally clicks on the delete icon.

**Comment by oliverheywood451** [comment]
A "safer" delete could be done in a lot of places. On the buyer side, deleting personal Addresses, deleting personal credit cards, canceling the order, and removing lineitems from the order (this last one is easier to fix). On the seller side, delete product, category, address, user, usergroup. 

Its worth thinking about an "undo" toastr instead of an "are you sure" interrupt modal. Once users get used to how the site works, constant "are you sure" boxes just slow things down. "undo" toastrs can be ignored. It might be too much effort, but worth thinking about how we would do it.

**Comment by oliverheywood451** [comment]
Maybe someday we can have undo *sigh* but for now, just are you sure.
